language: python
python:
- '2.7'
virtualenv:
  system_site_packages: false
before_install:
- export TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"
- REPO=`pwd`
- echo $REPO
- echo $TRAVIS_TAG
- pwd
- sudo apt-get -qq update
- sudo apt-get -qq install python2.7 python-pip git python-nfqueue
install:
- export PYTHONIOENCODING=UTF8
- python setup.py install
script:
- nosetests -v
notifications:
  irc:
  - irc.freenode.org#conpot-dev
