language: python
python:
- '2.7'
before_install:
- sudo apt-get -q update
- sudo apt-get -q install python-nfqueue
install:
- python2.7 setup.py install
script:
- nosetests -v
notifications:
  irc:
    channels:
      - irc.freenode.org#conpot-dev
    use_notice: true
    skip_join: true
